# Generated by Django 5.1.5 on 2025-01-27 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('nome', models.CharField(max_length=50)),
                ('defesa', models.IntegerField()),
                ('ataque', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('descricao', models.TextField()),
                ('classe', models.CharField(choices=[('Comunidade', 'Comunidade'), ('Bug', 'Bug'), ('Dark', 'Dark'), ('Dragon', 'Dragon'), ('Electric', 'Electric'), ('Fairy', 'Fairy'), ('Fighting', 'Fighting'), ('Fire', 'Fire'), ('Flying', 'Flying'), ('Ghost', 'Ghost'), ('Grass', 'Grass'), ('Ground', 'Ground'), ('Ice', 'Ice'), ('Normal', 'Normal'), ('Poison', 'Poison'), ('Psychic', 'Psychic'), ('Rock', 'Rock'), ('Steel', 'Steel'), ('Water', 'Water')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='user/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
